USE [master]
GO

/****** Object:  Database [Baddit]    Script Date: 27/06/2023 11:03:39 ******/
CREATE DATABASE [Baddit]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Baddit', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Baddit.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Baddit_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Baddit_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Baddit].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Baddit] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Baddit] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Baddit] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Baddit] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Baddit] SET ARITHABORT OFF 
GO

ALTER DATABASE [Baddit] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Baddit] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Baddit] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Baddit] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Baddit] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Baddit] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Baddit] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Baddit] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Baddit] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Baddit] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Baddit] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Baddit] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Baddit] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Baddit] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Baddit] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Baddit] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Baddit] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Baddit] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Baddit] SET  MULTI_USER 
GO

ALTER DATABASE [Baddit] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Baddit] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Baddit] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Baddit] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Baddit] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Baddit] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Baddit] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Baddit] SET  READ_WRITE 
GO

