	USE MASTER
	GO

	IF EXISTS(SELECT * FROM sys.databases WHERE name = 'Baddit')
		DROP DATABASE Baddit
	GO

	CREATE DATABASE Baddit
	GO

	USE Baddit
	GO

	CREATE TABLE User_Baddit
	(
		ID INT PRIMARY KEY IDENTITY,
		Email VARCHAR(100) UNIQUE NOT NULL, 
		UserName VARCHAR(55) NOT NULL, 
		LastName VARCHAR(55) NOT NULL,
		DateBirth DATE NOT NULL,
		NickUser VARCHAR(25) UNIQUE NOT NULL,
		PasswordUser VARBINARY(MAX) NOT NULL,
		SaldPassword VARCHAR(MAX) NOT NULL,
		UserPhoto VARBINARY(MAX) NOT NULL
	);
	GO 

	CREATE TABLE Forum
	(
		ID INT IDENTITY PRIMARY KEY,
		Creator VARCHAR(100) FOREIGN KEY REFERENCES User_Baddit(Email),
		ForumName VARCHAR(55) UNIQUE NOT NULL,
		DescriptionForum VARCHAR(255) NOT NULL
	);
	GO

	CREATE TABLE Roles
	(
		ID INT IDENTITY PRIMARY KEY,
		RoleName VARCHAR(55),
		Forum INT FOREIGN KEY REFERENCES Forum(ID)
	);
	GO


	CREATE TABLE Permission
	(
		ID INT PRIMARY KEY IDENTITY,
		PermissionName VARCHAR(50)
	);
	GO

	CREATE TABLE RolePermissions 
	(
		ID INT PRIMARY KEY IDENTITY,
		RoleId INT FOREIGN KEY REFERENCES Roles(ID),
		PermissionId INT FOREIGN KEY REFERENCES Permission(ID)
	);
	GO

	CREATE TABLE ParticipantForum
	(
		ID INT IDENTITY PRIMARY KEY,
		Forum INT FOREIGN KEY REFERENCES Forum(ID), 
		ParticipantForum INT FOREIGN KEY REFERENCES User_Baddit(ID)
	);
	GO

	CREATE TABLE Post
	(
		ID INT IDENTITY PRIMARY KEY,
		Tittle VARCHAR(100) NOT NULL,
		PostText VARCHAR(MAX) NOT NULL,
		PostDate DATE NOT NULL,
		Forum INT FOREIGN KEY REFERENCES Forum(ID), 
		Participant INT FOREIGN KEY REFERENCES User_Baddit(ID)
	);
	GO


	CREATE TABLE Comment 
	(
		ID INT IDENTITY PRIMARY KEY,
		Participant INT FOREIGN KEY REFERENCES User_Baddit(ID),
		PostComment INT FOREIGN KEY REFERENCES Post(ID),
		CommentText VARCHAR(MAX) NOT NULL
	);
	GO


	CREATE TABLE UpvoteDownvote
	(
		ID INT IDENTITY PRIMARY KEY,
		Participant INT FOREIGN KEY REFERENCES User_Baddit(ID),
		Post INT FOREIGN KEY REFERENCES Post(ID)
	);

	CREATE TABLE ImageData(
		ID INT IDENTITY PRIMARY KEY,
		Photo VARBINARY(MAX) NOT NULL,  
	);
	GO

	CREATE TABLE LocationPhoto(
		ID INT IDENTITY PRIMARY KEY,
		Nome VARCHAR(60) NOT NULL,
		Photo INT FOREIGN KEY REFERENCES ImageData(ID),
		Participant INT FOREIGN KEY REFERENCES User_Baddit(ID)
	);
	GO